[package]
name = "giaw-shared"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
aunty = { git = "https://github.com/Radbuglet/aunty.git", rev = "a7ce9d9225ff446543ed998afdd645e145d2d3f4" }
autoken = "0.1.0"
cbit = "0.1.0"
derive-where = "1.2.7"
enum-map = "2.7.3"
extend = "1.2.0"
glam = "0.21.3"
hashbrown = "0.14.3"
rustc-hash = "1.1.0"
smallvec = "1.11.2"
